
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: ingress-nginx
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app1.vindpro.dev
    http:
      paths:
      - backend:
          serviceName: hello-k8s-01
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: hello-k8s-01
  namespace: default
spec:
  type: ExternalName
  externalName: hello-kubernetes-first.default.svc.cluster.local
  ports:
  - port: 80
